name: brilliant
description: "Brilliant interactive app for learning English"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/books/
    - assets/vocabulary/words/easy_1.json
    - assets/vocabulary/words/easy_2.json
    - assets/vocabulary/words/easy_3.json
    - assets/vocabulary/words/easy_4.json
    - assets/vocabulary/words/easy_5.json
    - assets/vocabulary/words/medium_1.json
    - assets/vocabulary/words/medium_2.json
    - assets/vocabulary/words/medium_3.json
    - assets/vocabulary/words/medium_4.json
    - assets/vocabulary/words/medium_5.json
    - assets/vocabulary/words/hard_1.json
    - assets/vocabulary/words/hard_2.json
    - assets/vocabulary/words/hard_3.json
    - assets/vocabulary/words/hard_4.json
    - assets/vocabulary/words/hard_5.json
